/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'OhadR' at '11/6/15 11:50 PM' with Gradle 2.6
 *
 * @author OhadR, @date 11/6/15 11:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
